name: Scrape mec.ca

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1,11,21,31,41,51 * * * *'

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Scrape home page
        run: node scrapeHomepage.js > data/homepage.json
      - name: Scrape daily deals page
        run: node scrapeDailyDeals.js > data/dailydeals.json
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add data
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
