name: Scrape mec.ca

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1,11,21,31,41,51 * * * *'

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g bats
      - run: bats -v
